// Code generated by codegen; DO NOT EDIT.

package services

import (
	"context"
	"github.com/cloudquery/cloudquery/plugins/source/heroku/client"
	"github.com/cloudquery/cq-provider-sdk/provider/schema"
	"github.com/pkg/errors"
)

func AddOns() *schema.Table {
	return &schema.Table{
		Name:      "heroku_add_on",
		Resolver:  fetchAddOns,
		Multiplex: client.NoMultiplex,
		Columns: []schema.Column{
			{
				Name: "actions",
				Type: schema.TypeJSON,
			},
			{
				Name: "addon_service",
				Type: schema.TypeJSON,
			},
			{
				Name: "app",
				Type: schema.TypeJSON,
			},
			{
				Name: "billed_price",
				Type: schema.TypeJSON,
			},
			{
				Name: "billing_entity",
				Type: schema.TypeJSON,
			},
			{
				Name: "config_vars",
				Type: schema.TypeStringArray,
			},
			{
				Name: "created_at",
				Type: schema.TypeJSON,
			},
			{
				Name: "id",
				Type: schema.TypeString,
			},
			{
				Name: "name",
				Type: schema.TypeString,
			},
			{
				Name: "plan",
				Type: schema.TypeJSON,
			},
			{
				Name: "provider_id",
				Type: schema.TypeString,
			},
			{
				Name: "state",
				Type: schema.TypeString,
			},
			{
				Name: "updated_at",
				Type: schema.TypeJSON,
			},
			{
				Name: "web_url",
				Type: schema.TypeString,
			},
		},
	}
}

func fetchAddOns(ctx context.Context, meta schema.ClientMeta, _ *schema.Resource, res chan<- interface{}) error {
	c := meta.(*client.Client)
	v, err := c.Heroku.AddOnList(ctx, nil)
	if err != nil {
		return errors.WithStack(err)
	}
	res <- v
	return nil
}
