// Code generated by codegen; DO NOT EDIT.

package services

import (
	"context"
	"github.com/cloudquery/cloudquery/plugins/source/heroku/client"
	"github.com/cloudquery/plugin-sdk/schema"
	"github.com/pkg/errors"
)

func Stacks() *schema.Table {
	return &schema.Table{
		Name:      "heroku_stack",
		Resolver:  fetchStacks,
		Multiplex: client.NoMultiplex,
		Columns: []schema.Column{
			{
				Name: "created_at",
				Type: schema.TypeJSON,
			},
			{
				Name: "default",
				Type: schema.TypeBool,
			},
			{
				Name: "id",
				Type: schema.TypeString,
				CreationOptions: schema.ColumnCreationOptions{
					PrimaryKey: true,
				},
			},
			{
				Name: "name",
				Type: schema.TypeString,
			},
			{
				Name: "state",
				Type: schema.TypeString,
			},
			{
				Name: "updated_at",
				Type: schema.TypeJSON,
			},
		},
	}
}

func fetchStacks(ctx context.Context, meta schema.ClientMeta, _ *schema.Resource, res chan<- interface{}) error {
	c := meta.(*client.Client)
	v, err := c.Services.Heroku.StackList(ctx, nil)
	if err != nil {
		return errors.WithStack(err)
	}
	res <- v
	return nil
}
