// Code generated by codegen; DO NOT EDIT.

package services

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	faker "github.com/cloudquery/faker/v3"
	"github.com/cloudquery/cloudquery/plugins/source/heroku/client"
	"github.com/julienschmidt/httprouter"
	heroku "github.com/heroku/heroku-go/v5"
	{{range .MockImports}}
  "{{.}}"
  {{end}}
)

func create{{.HerokuStructName | Pluralize }}() (*client.Services, error) {
	var item heroku.{{.HerokuStructName}}
	if err := faker.FakeData(&item); err != nil {
		return nil, err
	}
	mux := httprouter.New()
	mux.GET("/{{.HerokuStructName | ToSnake }}", func(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {
		resp := []*heroku.{{.HerokuStructName}}{
			&item,
		}
		b, err := json.Marshal(resp)
		if err != nil {
			http.Error(w, "unable to marshal request: "+err.Error(), http.StatusBadRequest)
			return
		}
		if _, err := w.Write(b); err != nil {
			http.Error(w, "failed to write", http.StatusBadRequest)
			return
		}
	})
	ts := httptest.NewServer(mux)
	h := heroku.NewService(ts.Client())
	return &client.Services{
		Heroku: h,
	}, nil
}

func Test{{.HerokuStructName}}(t *testing.T) {
	client.HerokuMockTestHelper(t, {{.HerokuStructName | Pluralize}}(), create{{.HerokuStructName | Pluralize }}, client.TestOptions{})
}
